# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_story_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
